name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.5.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - pip
  - pip:
    - mlflow>=2.0
    - matplotlib
    - seaborn